server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: bhanu

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.example: DEBUG
